version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=funcionario
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=user
    ports:
      - '5432:5432'
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/funcionario
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=secret
